"""initial schema

Revision ID: 858129591171
Revises: 
Create Date: 2025-07-26 14:06:08.862553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858129591171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('loc_id', sa.Integer(), nullable=False),
    sa.Column('loc_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('loc_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('pass_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('u_email', sa.String(length=255), nullable=True),
    sa.Column('is_superUser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parking_lots',
    sa.Column('lot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_name', sa.String(length=120), nullable=False),
    sa.Column('loc_id', sa.Integer(), nullable=True),
    sa.Column('max_spot', sa.Integer(), nullable=True),
    sa.Column('lot_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loc_id'], ['locations.loc_id'], ),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_table('pspots',
    sa.Column('spot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('spot_no', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.lot_id'], ),
    sa.PrimaryKeyConstraint('spot_id'),
    sa.UniqueConstraint('lot_id', 'spot_no', name='uq_lot_spot')
    )
    op.create_table('book_lot',
    sa.Column('b_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.Column('end_time', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('b_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['pspots.spot_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('payment',
    sa.Column('p_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('p_time', sa.String(length=120), nullable=False),
    sa.Column('p_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['b_id'], ['book_lot.b_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('book_lot')
    op.drop_table('pspots')
    op.drop_table('parking_lots')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
